name: Rebuild documentation
on: workflow_dispatch
jobs:
    release-docs:
        runs-on: ubuntu-latest
        env:
            GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
            GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GH_TOKEN }}
            -   uses: gradle/wrapper-validation-action@v1
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 8
            -   name: Get latest release version number
                id: get_version
                uses: battila7/get-version-action@v2
            -   name: Build documentation
                env:
                    RELEASE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
                run: |
                    ./gradlew asciidoctor -Pversion="${RELEASE_VERSION}"
            -   name: Export Gradle Properties
                uses: micronaut-projects/github-actions/export-gradle-properties@master
            -   name: Publish to Github Pages
                if: success()
                uses: micronaut-projects/github-pages-deploy-action@master
                env:
                    BETA: ${{ steps.get_version.outputs.isPrerelase }}
                    TARGET_REPOSITORY: ${{ github.repository }}
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: build/asciidoc
                    DOC_FOLDER: latest
                    COMMIT_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
                    COMMIT_NAME: ${{ secrets.GIT_USER_NAME }}
                    VERSION: ${{ steps.get_version.outputs.version-without-v }}
            -   name: Run post-release
                if: success()
                uses: micronaut-projects/github-actions/post-release@master
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
